// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reseau.Web.Db;

namespace Reseau.Web.Migrations
{
    [DbContext(typeof(ReseauContext))]
    partial class ReseauContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reseau.Web.Gares.Gare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroRue")
                        .HasColumnType("int");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gares");
                });

            modelBuilder.Entity("Reseau.Web.Lignes.Ligne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DureeTrajet")
                        .HasColumnType("int");

                    b.Property<int>("GareArriveeId")
                        .HasColumnType("int");

                    b.Property<int>("GareDepartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GareArriveeId");

                    b.HasIndex("GareDepartId");

                    b.ToTable("Lignes");
                });

            modelBuilder.Entity("Reseau.Web.Lignes.Ligne", b =>
                {
                    b.HasOne("Reseau.Web.Gares.Gare", "GareArrivee")
                        .WithMany()
                        .HasForeignKey("GareArriveeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reseau.Web.Gares.Gare", "GareDepart")
                        .WithMany()
                        .HasForeignKey("GareDepartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
